version: 2.0

references:
  # Default actions to perform on each Emacs version
  default: &default-steps
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk add python3 make openjdk8 bash
      - run: test/tools/download-jar.py
      - run: make

# Enumerated list of Emacs versions
jobs:
  build:
    docker:
      - image: silex/emacs:25.3-alpine-dev
        entrypoint: sh
    <<: *default-steps

  test-emacs-25:
    docker:
      - image: silex/emacs:25.3-alpine-dev
        entrypoint: sh
    <<: *default-steps

  test-emacs-26:
    docker:
      - image: silex/emacs:26.1-alpine-dev
        entrypoint: sh
    <<: *default-steps

  test-emacs-master:
    docker:
      - image: silex/emacs:master-alpine-dev
        entrypoint: sh
    <<: *default-steps

# Executing in parallel
workflows:
  version: 2
  ci-test-matrix:
    jobs:
      - test-emacs-25
      - test-emacs-26
      - test-emacs-master
